<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" ui-sref="home">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Phalcon Starter Guide</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a ui-sref="home">Home</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a ui-sref="home.about">About</a>
                </li>
                <li>
                    <a ui-sref="home.contact">Contact us</a>
                </li>
                <li>
                    <a ui-sref="home.career">Career</a>
                </li>
                <li>
                    <a ui-sref="singlePage">Single Page</a>
                </li>
            </ul>
        </div>
    </div>
</nav>