<!DOCTYPE html>
    <html ng-app="PhalconStarterGuide" ng-controller="PhalconStarterGuide as psg">
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title update-title>Phalcon Starter Guide</title>
        <link href="vendors/bower_components/bootstrap/css/bootstrap.min.css" rel="stylesheet"> <!-- This si a bootstrap css file-->
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <base href="/">
        <?php echo $this->getContent(); ?>
        <div ui-view class="content-page"></div> <!-- This is where our app will be loaded -->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->baseurl; ?>';
        </script>
        <script type="text/javascript" src="vendors/bower_components/jquery/dist/jquery.min.js"></script> <!-- This is a Jquery file-->
        <script type="text/javascript" src="vendors/bower_components/bootstrap/js/bootstrap.min.js"></script> <!-- This is a Bootstrap file-->
        <script type="text/javascript" src="vendors/bower_components/angular/angular.min.js"></script> <!-- This is a Agular core file-->
        <script type="text/javascript" src="vendors/bower_components/angular-ui-router/release/angular-ui-router.min.js"></script> <!-- This file is for ui routing-->
        <script type="text/javascript" src="vendors/bower_components/oclazyload/dist/ocLazyLoad.min.js"></script> <!-- This file is for lazy loading of script file that will be user by application-->
        <script type="text/javascript" src="js/app.js"></script>   <!-- This file contains module declaration-->
        <script type="text/javascript" src="js/config.js"></script> <!-- This file is for routing configuration-->
        <script type="text/javascript" src="js/controllers/main.js"></script> <!-- This file contains the parent application controller. this will hanlde the first controller that will be use by app skeleton-->
        
    </body>
</html>
